
class Speaker:
    def __init__(self) -> None:
        ...

    def beep(self, note=60, seconds=0.2, volume=None) -> None:
        ...
    def start_beep(self, note=60, volume=None) -> None :
        ...
    def stop(self) -> None :
        ...
    def play_sound(self, name, volume=None) -> None :
        ...
    def start_sound(self, name, volume) -> None :
        ...
    def get_volume(self) -> int :
        ...
    def set_volume(self,volume) -> None :
        ...
        